### ISSUE TITLE
needletail other then bio to accelerate fasta parsing

### ISSUE THREAD

**Issue by jianshu93** [suchapalaver/krust#15]
Hello Team,

It seems needle tail is much faster than bio for fasta file parsing. For larger fasta files, parsing can also be parallelized. Is this doable?

Thanks,

Jianshu

**Comment by suchapalaver** [comment]
Sorry for the delayed reply. I'll look into this. Thanks for the suggestion.

**Comment by suchapalaver** [comment]
@jianshu93 Check out [this branch](https://github.com/suchapalaver/krust/tree/feature/use-needletail-for-fasta-parsing) for experimenting with `needletail`.

**Comment by suchapalaver** [comment]
@jianshu93 , I'd be interested if you think this is an improvement. I couldn't easily figure out how to parallelize processing the fasta records, what with `needletail`'s implementation of `next()`.
